bots = []

[flags]
enable_tool_selector_bot = false
enable_regex_tester_bot = false
enable_prompt_improver_bot = false
enable_dialog_log = false
enable_shell_log = false
enable_api_log = false
enable_autocat = true

[values]

[lists]
