[[bots]]
assistant_id = "asst_UKPOvP8rSR10dni9KQvZ2SS8"
name = "Unit test writer."
threads = []

[[bots]]
assistant_id = "asst_dBD4oegnFK6bwaoVG5RTIsaU"
name = "Pylint fixer bot"
threads = []

[[bots]]
assistant_id = "asst_mtbDzpfvbRtvatXiwIsOftwj"
name = "Docstring writer bot"
threads = []

[[bots]]
assistant_id = "asst_FsizGTcJbaYldKsaCF8deJWX"
name = "cat_markdown, insert, replace tool user."
threads = []

[flags]
enable_tool_selector_bot = false
enable_regex_tester_bot = false
enable_prompt_improver_bot = false
enable_dialog_log = false
enable_shell_log = false
enable_api_log = false
