[[bots]]
assistant_id = "asst_bjIt6pAYUFfyhmNcnkH9DBeg"
name = "Unit test writer."
threads = []


[flags]
enable_tool_selector_bot = false
enable_regex_tester_bot = false
enable_prompt_improver_bot = false
enable_dialog_log = false
enable_shell_log = false
enable_api_log = false
