[tox]
envlist =
    py312
    py313
    py314

requires =
    tox-uv>=1.28

[testenv]
extras =
    checkers
deps =
    # parameterized
    pytest>=7.4.4
    pytest-cov>=4.1.0
    toml;python_version<'3.11'
    pytest-benchmark>=4.0.0
    freezegun
    hypothesis>=6.96.0
    pytest-xdist>=3.5.0
    pytest-mock
    pytest-snapshot>=0.9.0
commands =
    pytest tests -q  --dist=loadfile --ignore=tests/test_snapshots --cov=ai_shell --cov-fail-under=35 -p no:benchmark
setenv =
    PYO3_USE_ABI3_FORWARD_COMPATIBILITY=1
