[[tasks]]
title = "Implement Ocean Waves Emojis"
description = "Implement ocean waves using emojis across the top line of the screen in the __main__.py file."
done_status = false
category = "feature"
source_code_ref = "__main__.py"
assignee = "developer"

[[tasks]]
title = "Implement ocean waves animation"
description = "Implement ocean waves across the top line of screen using a line of emojis."
done_status = false
category = "feature"
source_code_ref = "__main__.py"
assignee = "developer"

